# Generated by Django 4.2.13 on 2024-05-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MelissaTrasporti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('trasporto', models.BooleanField()),
                ('trattamento', models.BooleanField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='CentroSmaltimento',
        ),
        migrations.DeleteModel(
            name='Trasportatore',
        ),
    ]
