# Generated by Django 4.2.13 on 2024-06-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MelissaTrasporti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commessa',
            name='tipologia',
            field=models.TextField(help_text='Tipologia di RAEE', verbose_name='tipologia'),
        ),
    ]
