# Generated by Django 4.2.13 on 2024-06-10 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MelissaTrasporti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commessa',
            name='offerta',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='MelissaTrasporti.offerta', verbose_name='offerta di riferimento'),
        ),
    ]
