# Generated by Django 4.2.13 on 2024-05-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MelissaTrasporti', '0002_fornitore_delete_centrosmaltimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornitore',
            old_name='address',
            new_name='indirizzo',
        ),
        migrations.RenameField(
            model_name='fornitore',
            old_name='lat',
            new_name='latitudine',
        ),
        migrations.RenameField(
            model_name='fornitore',
            old_name='long',
            new_name='longitudine',
        ),
    ]
