# Generated by Django 4.2.13 on 2024-06-10 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MelissaTrasporti', '0003_alter_commessa_offerta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commessa',
            name='offerta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MelissaTrasporti.offerta', verbose_name='offerta di riferimento'),
        ),
    ]
