# Generated by Django 4.2.13 on 2024-05-31 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MelissaTrasporti', '0003_rename_address_fornitore_indirizzo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornitore',
            options={'verbose_name_plural': 'Fornitori'},
        ),
    ]
