# Generated by Django 4.2.13 on 2024-06-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MelissaTrasporti', '0004_alter_commessa_offerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='commessa',
            name='latitudine',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='commessa',
            name='longitudine',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='latitudine',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='offerta',
            name='longitudine',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
