# Generated by Django 5.1.2 on 2025-03-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commessa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.FloatField(verbose_name='Quantità')),
                ('tipologia', models.CharField(max_length=100)),
                ('produttore', models.CharField(max_length=200)),
                ('indirizzo', models.CharField(max_length=255, verbose_name='Luogo di ritiro')),
                ('provincia', models.CharField(max_length=50)),
                ('data_ritiro', models.CharField(default='DA FARE', max_length=100)),
                ('anno', models.IntegerField()),
                ('latitudine', models.FloatField(blank=True, null=True)),
                ('longitudine', models.FloatField(blank=True, null=True)),
                ('codice_commessa', models.CharField(max_length=100, unique=True)),
                ('data_creazione', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commessa',
                'verbose_name_plural': 'Commesse',
            },
        ),
        migrations.CreateModel(
            name='Offerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.FloatField(verbose_name='Quantità')),
                ('tipologia', models.CharField(max_length=100)),
                ('produttore', models.CharField(max_length=200)),
                ('indirizzo', models.CharField(max_length=255, verbose_name='Luogo di ritiro')),
                ('provincia', models.CharField(max_length=50)),
                ('data_ritiro', models.CharField(default='DA FARE', max_length=100)),
                ('anno', models.IntegerField()),
                ('latitudine', models.FloatField(blank=True, null=True)),
                ('longitudine', models.FloatField(blank=True, null=True)),
                ('codice_offerta', models.CharField(max_length=100, unique=True)),
                ('codice_commessa', models.CharField(blank=True, max_length=100, null=True)),
                ('data_offerta', models.DateField(blank=True, null=True)),
                ('garanzia_finanziaria', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Offerta',
                'verbose_name_plural': 'Offerte',
            },
        ),
    ]
