# Generated by Django 5.1.2 on 2025-04-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mappa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=150, verbose_name='Cognome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('registration_token', models.UUIDField(blank=True, default=None, editable=False, null=True, unique=True, verbose_name='Token Registrazione Finale')),
                ('status', models.CharField(choices=[('pending', 'In Attesa'), ('approved', 'Approvata'), ('completed', 'Completata')], default='pending', max_length=10, verbose_name='Stato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Richiesta')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data Approvazione')),
            ],
            options={
                'verbose_name': 'Richiesta di Registrazione',
                'verbose_name_plural': 'Richieste di Registrazione',
                'ordering': ['-created_at'],
            },
        ),
    ]
