# Generated by Django 5.1.2 on 2025-04-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mappa', '0002_pendingapproval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingApproval',
        ),
    ]
