# Generated by Django 5.1.2 on 2025-04-16 09:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mappa', '0003_delete_pendingapproval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Richiedente')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token Univoco')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('expires_at', models.DateTimeField(verbose_name='Data Scadenza')),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilizzato')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_token', to=settings.AUTH_USER_MODEL, verbose_name='Utente Registrato')),
            ],
            options={
                'verbose_name': 'Token di Registrazione',
                'verbose_name_plural': 'Token di Registrazione',
                'ordering': ['-created_at'],
            },
        ),
    ]
