"""
Django settings for MappaEcoPVTrasporti project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t^3z5qr!mv3z$_6*4%s(y$rbl$2us%jy^xeg#r*tq+vw^df*gx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Mappa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MappaEcoPVTrasporti.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MappaEcoPVTrasporti.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'Mappa', 'static'),
]


# Configurazione file media
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'

# Impostazioni Email per Produzione con SMTP (Webcloud.it)

# 1. Specifica il backend SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# 2. Inserisci l'host SMTP fornito da Webcloud.it
EMAIL_HOST = 'mail.webcloud.it'  # <-- SOSTITUISCI CON IL TUO HOST REALE!

# 3. Inserisci la porta SMTP fornita da Webcloud.it
EMAIL_PORT = 465 # <-- SOSTITUISCI CON LA TUA PORTA REALE! (587 è comune per TLS)

# 4. Specifica se usare TLS o SSL (MUTUALMENTE ESCLUSIVI!)
# Se usi la porta 587 (TLS/STARTTLS):
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# Se usi la porta 465 (SSL):
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True

# 5. Inserisci il nome utente SMTP (di solito l'email completa)
#    È MEGLIO usare variabili d'ambiente per sicurezza! Vedi sotto.
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'giulio.lazzaro@zilioenvironment.com') # <-- SOSTITUISCI O USA ENV VAR

# 6. Inserisci la password SMTP
#    È FORTEMENTE SCONSIGLIATO scriverla qui! Usa variabili d'ambiente.
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '1Mz8p0$w6') # <-- USA ASSOLUTAMENTE ENV VAR!

# 7. Email mittente predefinita (deve essere un'email valida gestita dal tuo account)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER # Spesso coincide con l'utente SMTP

# Email per errori server (opzionale, ma utile)
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Email dell'amministratore per le notifiche
ADMIN_EMAIL = 'tua_email_admin@example.com' # <-- Assicurati sia corretta

# URL di Login (necessario se usi @login_required)
LOGIN_URL = 'login'

# URL a cui reindirizzare dopo il login (se non c'è 'next')
# LOGIN_REDIRECT_URL = 'index' # Opzionale, la vista login gestisce già il redirect a 'index'

# URL a cui reindirizzare dopo il logout
# LOGOUT_REDIRECT_URL = 'login' # Opzionale, la vista logout gestisce già il redirect a 'login'
